import { describe,expect,it } from "vitest";
import { mockLeague } from "@/data/mockLeague";
import { calculatePowerRankings, calculateExpectedWins, normalizeMinMax, normalizeZScore, recentFormScores } from "@/lib/rankings";
import { seasonAnalytics, weeklyAnalytics } from "@/lib/analytics/leagueAnalytics";
import type { League } from "@/lib/domain";
describe("normalization",()=>{it("normalizes ordinary, negative and extreme values",()=>{expect(normalizeMinMax([-10,0,10])).toEqual([0,50,100]);expect(normalizeMinMax([0,0])).toEqual([50,50]);expect(normalizeMinMax([Number.POSITIVE_INFINITY,1]).every(Number.isFinite)).toBe(true);expect(normalizeZScore([5,5])).toEqual([50,50]);});});
describe("expected wins",()=>{it("ranks weekly high and low correctly",()=>{expect(calculateExpectedWins(mockLeague,"1").expectedWins).toBeGreaterThan(calculateExpectedWins(mockLeague,"10").expectedWins)});it("awards half credit for ties and ignores incomplete weeks",()=>{const l:League={id:"x",name:"x",season:1,currentWeek:2,teams:["a","b","c"].map(id=>({id,name:id,wins:0,losses:0,ties:1,pointsFor:10,pointsAgainst:10,roster:[]})),matchups:[{week:1,homeTeamId:"a",awayTeamId:"b",homeScore:10,awayScore:10,completed:true},{week:1,homeTeamId:"c",awayTeamId:"a",homeScore:5,awayScore:10,completed:false}]};expect(calculateExpectedWins(l,"a").expectedWins).toBe(.5);});});
describe("ranking engine",()=>{it("is deterministic, bounded, complete, and ordered",()=>{const a=calculatePowerRankings(mockLeague),b=calculatePowerRankings(mockLeague);expect(a).toEqual(b);expect(a).toHaveLength(10);expect(a.every(r=>Number.isFinite(r.powerScore)&&r.powerScore>=0&&r.powerScore<=100)).toBe(true);expect(a.map(r=>r.rank)).toEqual([1,2,3,4,5,6,7,8,9,10]);});it("supports movement",()=>{const base=calculatePowerRankings(mockLeague);const prior=Object.fromEntries(base.map(r=>[r.teamId,11-r.rank]));expect(calculatePowerRankings(mockLeague,prior).some(r=>r.rankChange!==0)).toBe(true);});it("recent form handles fewer, exactly, and more than three weeks",()=>{for(const count of [2,3,6])expect(Object.values(recentFormScores({...mockLeague,matchups:mockLeague.matchups.filter(m=>m.week<=count)})).every(Number.isFinite)).toBe(true);});});
describe("analytics",()=>{it("finds weekly extremes",()=>{const a=weeklyAnalytics(mockLeague,6);expect(a.highest?.score).toBe(152.3);expect(a.lowest?.score).toBe(104.8);expect(a.biggestBlowout).toBeTruthy();expect(a.closestMatchup).toBeTruthy();});it("finds luck and consistency extremes",()=>{const a=seasonAnalytics(mockLeague);expect(a.luckiest).toBeTruthy();expect(a.unluckiest).toBeTruthy();expect(a.mostConsistent.deviation).toBeLessThanOrEqual(a.mostVolatile.deviation);});});
