import "server-only";
import type { League, PowerRanking } from "@/lib/domain";
import { calculatePreseasonRankings } from "@/lib/preseason";
import { calculatePowerRankings } from "@/lib/rankings";
import type { PreseasonRankingsResult } from "@/lib/preseason";
import { publishPreseasonSnapshot, publishRegularSnapshot } from "./snapshots";
import type { SnapshotStore } from "./types";
import type { GeneratedArticleStore } from "@/lib/news/generated";
import { generateWeeklyRankingArticle } from "@/lib/news/weeklyArticle";

export function isAuthorizedPublicationRequest(authorization:string|null,secret:string|undefined){return Boolean(secret&&authorization===`Bearer ${secret}`)}
export function latestFullyCompletedWeek(league:League){const weeks=[...new Set(league.matchups.map(m=>m.week))];return Math.max(0,...weeks.filter(week=>{const games=league.matchups.filter(m=>m.week===week);return games.length>0&&games.every(game=>game.completed)}))}
export async function publishCurrentPreseason(store:SnapshotStore,league:League){return publishPreseasonSnapshot(store,league,calculatePreseasonRankings(league))}
export async function publishLatestCompletedWeek(store:SnapshotStore,league:League,articles?:GeneratedArticleStore){const week=latestFullyCompletedWeek(league);if(!week)return{status:"no-completed-week" as const,week:0};const snapshots=await store.all(league.id,league.season),existing=await store.byWeek(league.id,league.season,week,"regular");const previous=snapshots.filter(s=>s.week<week).at(-1);let snapshot=existing,created=false;if(!snapshot){let previousRanks:Record<string,number>|undefined;if(previous?.snapshotType==="regular")previousRanks=Object.fromEntries((previous.result as PowerRanking[]).map(r=>[r.teamId,r.rank]));else if(previous?.snapshotType==="preseason")previousRanks=Object.fromEntries((previous.result as PreseasonRankingsResult).rankings.map(r=>[r.teamId,r.rank]));const frozenLeague={...league,currentWeek:week,matchups:league.matchups.filter(m=>m.week<=week)},rankings=calculatePowerRankings(frozenLeague,previousRanks),result=await publishRegularSnapshot(store,frozenLeague,week,rankings);created=result.created;snapshot=await store.byWeek(league.id,league.season,week,"regular");if(!snapshot)throw new Error("Published snapshot could not be read back.")}if(!articles)return{status:created?"published" as const:"already-published" as const,week,snapshotId:snapshot.id};const existingArticle=await articles.bySnapshot(snapshot.id);if(existingArticle)return{status:created?"published" as const:"already_published" as const,week,snapshotId:snapshot.id,articleSlug:existingArticle.slug};const previousRegular=previous?.snapshotType==="regular"?previous as import("./types").PublishedSnapshot<PowerRanking[]>:undefined,article=generateWeeklyRankingArticle(snapshot as import("./types").PublishedSnapshot<PowerRanking[]>,previousRegular),published=await articles.publish(article,league.id);return{status:created?"published" as const:"article_repaired" as const,week,snapshotId:snapshot.id,articleSlug:published.article.slug}}
