import "server-only";
import type { League, PowerRanking } from "@/lib/domain";
import type { PreseasonRankingsResult } from "@/lib/preseason";
import { createSupabaseServerClient } from "./server";
import type { PublishedSnapshot, SnapshotStore, SnapshotType } from "./types";

export function mapSnapshotRow(row:Record<string,unknown>):PublishedSnapshot{return{id:Number(row.id),leagueId:String(row.league_id),leagueName:String(row.league_name),season:Number(row.season),week:Number(row.week),snapshotType:row.snapshot_type as SnapshotType,label:String(row.label),publishedAt:String(row.published_at),league:row.league_data as League,result:row.result_data as PublishedSnapshot["result"]}}
// Supabase's fluent query builder changes its generic type after each filter.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function supabaseSnapshotStore():SnapshotStore|null{const db=createSupabaseServerClient();if(!db)return null;const query=async(leagueId:string,season:number,extra:(q:any)=>any)=>{let q=db.from("ranking_snapshots").select("id,league_id,league_name,season,week,snapshot_type,label,published_at,league_data,result_data").eq("league_id",leagueId).eq("season",season).not("published_at","is",null);q=extra(q);const {data,error}=await q;if(error)throw new Error(`Snapshot read failed: ${error.message}`);return data};return{async publish(payload){const {data,error}=await db.rpc("publish_ranking_snapshot",{payload});if(error)throw new Error(`Snapshot publication failed: ${error.message}`);const row=Array.isArray(data)?data[0]:data;return{snapshotId:Number(row.snapshot_id),created:Boolean(row.created)}},async latest(leagueId,season,type){const data=await query(leagueId,season,q=>{if(type)q=q.eq("snapshot_type",type);return q.order("week",{ascending:false}).order("published_at",{ascending:false}).limit(1)});return data?.[0]?mapSnapshotRow(data[0] as Record<string,unknown>):null},async byWeek(leagueId,season,week,type){const data=await query(leagueId,season,q=>q.eq("week",week).eq("snapshot_type",type).limit(1));return data?.[0]?mapSnapshotRow(data[0] as Record<string,unknown>):null},async all(leagueId,season){const data=await query(leagueId,season,q=>q.order("week",{ascending:true}));return(data??[]).map(row=>mapSnapshotRow(row as Record<string,unknown>))}}}

const regularTeams=(league:League,rankings:PowerRanking[])=>rankings.map(r=>{const team=league.teams.find(t=>t.id===r.teamId)!;return{team_id:r.teamId,team_name:team.name,rank:r.rank,power_score:r.powerScore,previous_rank:r.previousRank??null,rank_change:r.rankChange??null,scoring_score:r.components.scoring,recent_form_score:r.components.recentForm,record_score:r.components.record,expected_wins_score:r.components.expectedWins,roster_score:r.components.roster,schedule_score:r.components.schedule,points_per_game:r.pointsPerGame,expected_wins:r.expectedWins,expected_win_pct:r.expectedWinPct,luck:r.luck,explanation:r.explanation}});
export function regularSnapshotPayload(league:League,week:number,rankings:PowerRanking[]){return{league_id:league.id,league_name:league.name,season:league.season,week,snapshot_type:"regular",label:`Week ${week} Power Rankings`,published_at:new Date().toISOString(),league_data:{...league,currentWeek:week},result_data:rankings,teams:regularTeams(league,rankings),positions:[],players:[]}}
export function preseasonSnapshotPayload(league:League,result:PreseasonRankingsResult){const teams=result.rankings.map(r=>({team_id:r.teamId,team_name:league.teams.find(t=>t.id===r.teamId)!.name,rank:r.rank,power_score:r.overallScore,previous_rank:null,rank_change:null,scoring_score:0,recent_form_score:0,record_score:0,expected_wins_score:0,roster_score:r.overallScore,schedule_score:0,points_per_game:0,expected_wins:0,expected_win_pct:0,luck:0,explanation:r.explanation}));const positions=result.rankings.flatMap(r=>Object.values(r.positionGroups).map(g=>({team_id:r.teamId,position_group:g.group,position_rank:g.rank,position_score:g.score,raw_value:g.rawValue,starter_value:g.starterValue,depth_value:g.depthValue,starter_score:g.starterScore,depth_score:g.depthScore,top_starter_vor:g.topStarterValue,first_depth_vor:g.firstDepthValue,total_useful_depth_vor:g.totalUsefulDepthValue,explanation:g.explanation})));const players=result.rankings.flatMap(r=>r.contributions.map(p=>({team_id:r.teamId,player_id:p.playerId,player_name:p.name,position:p.position,assigned_slot:p.assignedSlot??null,season_projected_points:p.seasonProjectedPoints,replacement_projected_points:p.replacementLevel,raw_vor:p.rawVOR,usable_vor:p.usableVOR,contribution_multiplier:p.contributionMultiplier,final_contribution:p.finalContribution,contribution_role:p.role})));return{league_id:league.id,league_name:league.name,season:league.season,week:0,snapshot_type:"preseason",label:"Post-Draft Preseason Rankings",published_at:new Date().toISOString(),league_data:league,result_data:result,teams,positions,players}}
export async function publishPreseasonSnapshot(store:SnapshotStore,league:League,result:PreseasonRankingsResult){return store.publish(preseasonSnapshotPayload(league,result))}
export async function publishRegularSnapshot(store:SnapshotStore,league:League,week:number,rankings:PowerRanking[]){if(new Set(rankings.map(r=>r.teamId)).size!==league.teams.length)throw new Error("Refusing to publish a partial team snapshot.");return store.publish(regularSnapshotPayload(league,week,rankings))}
export async function getLatestPublishedSnapshot(leagueId:string,season:number,type?:SnapshotType){return supabaseSnapshotStore()?.latest(leagueId,season,type)??null}
export async function getPreseasonPublishedSnapshot(leagueId:string,season:number){return supabaseSnapshotStore()?.byWeek(leagueId,season,0,"preseason")??null}
export async function getPublishedSnapshotForWeek(leagueId:string,season:number,week:number){return supabaseSnapshotStore()?.byWeek(leagueId,season,week,"regular")??null}
export async function getSeasonSnapshots(leagueId:string,season:number){return supabaseSnapshotStore()?.all(leagueId,season)??[]}
export async function getPreviousPublishedSnapshot(leagueId:string,season:number,week:number){const all=await getSeasonSnapshots(leagueId,season);return all.filter(s=>s.week<week).at(-1)??null}
