import type { League, Player } from "@/lib/domain";
import type { EspnLeagueResponse } from "./types";
import type { EspnPlayer } from "./schemas";
const positions:Record<number,string>={1:"QB",2:"RB",3:"WR",4:"TE",5:"K",16:"D/ST"};
const slots:Record<number,string>={0:"QB",2:"RB",3:"RB/WR",4:"WR",5:"WR/TE",6:"TE",7:"SUPERFLEX",16:"D/ST",17:"K",20:"BE",21:"IR",23:"FLEX"};
const proTeams:Record<number,string>={0:"FA",1:"ATL",2:"BUF",3:"CHI",4:"CIN",5:"CLE",6:"DAL",7:"DEN",8:"DET",9:"GB",10:"TEN",11:"IND",12:"KC",13:"LV",14:"LAR",15:"MIA",16:"MIN",17:"NE",18:"NO",19:"NYG",20:"NYJ",21:"PHI",22:"ARI",23:"PIT",24:"LAC",25:"SF",26:"SEA",27:"TB",28:"WAS",29:"CAR",30:"JAX",33:"BAL",34:"HOU"};
export function getSeasonProjectedPoints(player:EspnPlayer,season:number){return player.stats?.find(stat=>stat.seasonId===season&&stat.scoringPeriodId===0&&stat.statSourceId===1&&stat.statSplitTypeId===0)?.appliedTotal;}
export function getSeasonActualPoints(player:EspnPlayer,season:number){return player.stats?.find(stat=>stat.seasonId===season&&stat.scoringPeriodId===0&&stat.statSourceId===0&&stat.statSplitTypeId===0)?.appliedTotal;}
export function getWeeklyProjectedPoints(player:EspnPlayer,season:number,week:number){return player.stats?.find(stat=>stat.seasonId===season&&stat.scoringPeriodId===week&&stat.statSourceId===1&&stat.statSplitTypeId===1)?.appliedTotal;}
export function getWeeklyActualPoints(player:EspnPlayer,season:number,week:number){return player.stats?.find(stat=>stat.seasonId===season&&stat.scoringPeriodId===week&&stat.statSourceId===0&&stat.statSplitTypeId===1)?.appliedTotal;}
export function parseEspnLeague(raw:EspnLeagueResponse):League{const currentWeek=raw.status?.currentMatchupPeriod??raw.status?.latestScoringPeriod??1;const teams=raw.teams.map(team=>{const overall=team.record?.overall;const roster:Player[]=(team.roster?.entries??[]).flatMap(entry=>{const player=entry.playerPoolEntry?.player;if(!player)return[];const slot=slots[entry.lineupSlotId]??`Slot ${entry.lineupSlotId}`;return [{id:String(player.id),name:player.fullName??`Player ${player.id}`,position:positions[player.defaultPositionId??-1]??"Unknown",eligibleSlots:[...new Set((player.eligibleSlots??[]).map(id=>slots[id]).filter(Boolean))],proTeam:proTeams[player.proTeamId??-1]??(player.proTeamId===undefined?undefined:String(player.proTeamId)),slot,isStarter:slot!=="BE"&&slot!=="IR",seasonProjectedPoints:getSeasonProjectedPoints(player,raw.seasonId),seasonActualPoints:getSeasonActualPoints(player,raw.seasonId),weeklyProjectedPoints:getWeeklyProjectedPoints(player,raw.seasonId,currentWeek),weeklyActualPoints:getWeeklyActualPoints(player,raw.seasonId,currentWeek)??entry.playerPoolEntry?.appliedStatTotal}]});const fallbackName=[team.location,team.nickname].filter(Boolean).join(" ")||`Team ${team.id}`;return {id:String(team.id),name:team.name??fallbackName,abbreviation:team.abbrev,logoUrl:team.logo,wins:overall?.wins??0,losses:overall?.losses??0,ties:overall?.ties??0,pointsFor:overall?.pointsFor??0,pointsAgainst:overall?.pointsAgainst??0,roster}});const matchups=raw.schedule.flatMap(game=>game.away?[{week:game.matchupPeriodId,homeTeamId:String(game.home.teamId),awayTeamId:String(game.away.teamId),homeScore:game.home.totalPoints??0,awayScore:game.away.totalPoints??0,completed:game.winner==="HOME"||game.winner==="AWAY"||game.winner==="TIE"}]:[]);const configured=raw.settings?.rosterSettings?.lineupSlotCounts??{};const rosterSlotCounts=Object.fromEntries(Object.entries(configured).filter(([,count])=>count>0).map(([id,count])=>[slots[Number(id)]??`Slot ${id}`,count]));return {id:String(raw.id),name:raw.settings?.name??"ESPN Fantasy League",season:raw.seasonId,currentWeek,teams,matchups,rosterSlotCounts};}
