import "server-only";import {createSupabaseServerClient} from "@/lib/supabase/server";import type {EspnErrorCode} from "@/lib/espn/client";import {getLatestPublishedSnapshot} from "@/lib/supabase/snapshots";
export type IntegrationHealthStatus="healthy"|"authentication_failed"|"configuration_error"|"network_error"|"rate_limited"|"service_error"|"malformed_response"|"unknown";
export type ConnectionDisplayState="connected"|"needs_attention"|"not_recorded"|"not_configured"|"status_unavailable";
export const connectionLabel=(state:ConnectionDisplayState)=>({connected:"✓ Connected",needs_attention:"⚠ Needs Attention",not_recorded:"Not Recorded",not_configured:"Not Configured",status_unavailable:"Status Unavailable"})[state];
export interface HealthRow{status?:unknown;last_success_at?:unknown;last_failure_at?:unknown;last_failure_reason?:unknown;last_successful_publish_at?:unknown}
export const safeFailureStatus=(code:EspnErrorCode):IntegrationHealthStatus=>({AUTH:"authentication_failed",CONFIG:"configuration_error",NETWORK:"network_error",RATE_LIMITED:"rate_limited",MALFORMED:"malformed_response",NOT_FOUND:"service_error",UNAVAILABLE:"service_error"})[code] as IntegrationHealthStatus;
const time=(value:unknown)=>typeof value==="string"&&Number.isFinite(Date.parse(value))?Date.parse(value):null;
export function resolveConnectionState(row:HealthRow|null,configured=true):ConnectionDisplayState{if(!configured)return"not_configured";if(!row)return"not_recorded";const success=time(row.last_success_at),failure=time(row.last_failure_at);if(success!==null&&(failure===null||success>failure))return"connected";if(failure!==null&&(success===null||failure>=success))return"needs_attention";if(row.status==="healthy")return"connected";return row.status&&row.status!=="unknown"?"needs_attention":"not_recorded"}
async function persist(values:Record<string,unknown>){const db=createSupabaseServerClient();if(!db)return false;const{error}=await db.from("integration_status").upsert({integration:"espn",...values,updated_at:new Date().toISOString()},{onConflict:"integration"});if(error)throw new Error(`Integration health persistence failed: ${error.message}`);return true}
export async function recordEspnSuccess(now=new Date()){const timestamp=now.toISOString();return persist({status:"healthy",last_success_at:timestamp,last_failure_at:null,last_failure_reason:null})}
export async function recordEspnFailure(code:EspnErrorCode,now=new Date()){const status=safeFailureStatus(code);return persist({status,last_failure_at:now.toISOString(),last_failure_reason:status})}
export async function recordPublishSuccess(now=new Date()){return persist({status:"healthy",last_successful_publish_at:now.toISOString()})}
export async function getPipelineHealth(){const db=createSupabaseServerClient(),configured=Boolean(process.env.ESPN_LEAGUE_ID&&process.env.ESPN_SEASON&&process.env.ESPN_S2&&process.env.ESPN_SWID);let data:HealthRow|null=null,statusReadFailed=false;if(db){const result=await db.from("integration_status").select("status,last_success_at,last_failure_at,last_failure_reason,last_successful_publish_at").eq("integration","espn").maybeSingle();if(result.error)statusReadFailed=true;else data=result.data as HealthRow|null}const connectionState=statusReadFailed?"status_unavailable" as const:resolveConnectionState(data,configured),season=Number(process.env.ESPN_SEASON),leagueId=process.env.ESPN_LEAGUE_ID;let snapshot=null;try{snapshot=leagueId&&Number.isInteger(season)?await getLatestPublishedSnapshot(leagueId,season,"regular"):null}catch{}return{espn:{configured,authenticated:connectionState==="connected",connectionState,status:String(data?.status??"unknown"),lastSuccessfulFetchAt:data?.last_success_at??null,lastFailureAt:data?.last_failure_at??null,lastFailureReason:data?.last_failure_reason??null},snapshots:{latestPublishedSeason:snapshot?.season??null,latestPublishedWeek:snapshot?.week??null,latestPublishedAt:snapshot?.publishedAt??null},cron:{lastSuccessfulPublishAt:data?.last_successful_publish_at??null,nextExpectedPublishDay:"Tuesday"}}}
