import "server-only";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { GeneratedNewsArticle } from "./types";

export interface GeneratedArticleStore {
  publish(article:Omit<GeneratedNewsArticle,"id">,leagueId:string):Promise<{article:GeneratedNewsArticle;created:boolean}>;
  bySnapshot(snapshotId:number):Promise<GeneratedNewsArticle|null>;
  bySlug(slug:string):Promise<GeneratedNewsArticle|null>;
  allPublished():Promise<GeneratedNewsArticle[]>;
}
export function mapGeneratedArticle(row:Record<string,unknown>):GeneratedNewsArticle{return{id:Number(row.id),snapshotId:Number(row.snapshot_id),articleType:"weekly_power_rankings",title:String(row.title),slug:String(row.slug),season:Number(row.season),week:Number(row.week),snapshotType:"regular",snapshotWeek:Number(row.week),publishedAt:String(row.published_at).slice(0,10),summary:String(row.summary),status:"published",heroLabel:"Automated power report",tags:["Power Rankings",`Week ${Number(row.week)}`],body:"",generatedContent:row.body as GeneratedNewsArticle["generatedContent"]}}
export function supabaseGeneratedArticleStore():GeneratedArticleStore|null{const db=createSupabaseServerClient();if(!db)return null;const select="id,snapshot_id,title,slug,season,week,published_at,summary,body";return{async publish(article,leagueId){const {data,error}=await db.rpc("publish_weekly_news_article",{payload:{league_id:leagueId,season:article.season,week:article.week,snapshot_id:article.snapshotId,article_type:article.articleType,title:article.title,slug:article.slug,summary:article.summary,body:article.generatedContent,status:article.status,published_at:article.publishedAt}});if(error)throw new Error(`Article publication failed: ${error.message}`);const result=Array.isArray(data)?data[0]:data,stored=await this.bySnapshot(article.snapshotId);if(!stored)throw new Error("Published article could not be read back.");return{article:stored,created:Boolean(result.created)}},async bySnapshot(snapshotId){const {data,error}=await db.from("news_articles").select(select).eq("snapshot_id",snapshotId).eq("status","published").maybeSingle();if(error)throw new Error(`Article read failed: ${error.message}`);return data?mapGeneratedArticle(data as Record<string,unknown>):null},async bySlug(slug){const {data,error}=await db.from("news_articles").select(select).eq("slug",slug).eq("status","published").maybeSingle();if(error)throw new Error(`Article read failed: ${error.message}`);return data?mapGeneratedArticle(data as Record<string,unknown>):null},async allPublished(){const {data,error}=await db.from("news_articles").select(select).eq("status","published").order("season",{ascending:false}).order("week",{ascending:false}).order("published_at",{ascending:false});if(error)throw new Error(`Article read failed: ${error.message}`);return(data??[]).map(row=>mapGeneratedArticle(row as Record<string,unknown>))}}}
